name: Keep Alive

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        run: curl -s https://portfolio-wivy.onrender.com/api/scores?mode=easy
